-- IDN Canonical Schema Contract v3 :: Signals domain governance contract
-- Release candidate canonical-v3-signals. Execute only through the guarded release runner.
--
-- GENERATED FILE. Edit gen_contract_v3.py and regenerate; do not hand-edit.
--
-- Registers every object created by 70-77 in the metadata catalogs so that
-- meta.table_catalog and meta.column_catalog describe them, and declares the
-- Signals application access contract. The generator fails if any live column
-- lacks a meaning or any annotation names a column that does not exist, so this
-- file cannot drift from the schema it documents.

begin;

insert into meta.object_annotation
  (schema_name, object_name, object_kind, purpose, row_grain,
   owning_domain, authority, pii_class, lifecycle_state, replacement_object)
values
  ('signals', 'account_metric', 'table', 'Append-only observation of an account level metric at a point in time', 'One metric observation', 'signals', 'source evidence', 'none', 'active', null),
  ('signals', 'account_score', 'table', 'Append-only account scoring history retained with the model that produced it', 'One account and scoring instant', 'signals', 'derived model output', 'internal', 'active', null),
  ('signals', 'conference', 'table', 'External conference whose programme is used for speaker prospecting', 'One conference edition', 'signals', 'source evidence', 'none', 'active', null),
  ('signals', 'conference_session', 'table', 'Programme session at an external conference', 'One session', 'signals', 'source evidence', 'internal', 'active', null),
  ('signals', 'content_cluster', 'table', 'Generated topic cluster over content items for a named preset', 'One generated cluster', 'signals', 'derived model output', 'internal', 'active', null),
  ('signals', 'content_cluster_member', 'table', 'Membership of a content item in a generated cluster, replacing an identifier array', 'One cluster and item', 'signals', 'derived model output', 'none', 'active', null),
  ('signals', 'content_github_repo', 'table', 'GitHub repository detail for a content item of kind github_repo', 'One repository', 'signals', 'observed platform value', 'internal', 'active', null),
  ('signals', 'content_linkedin_post', 'table', 'LinkedIn specific detail for a content item of kind linkedin_post', 'One LinkedIn post', 'signals', 'observed platform value', 'internal', 'active', null),
  ('signals', 'content_x_post', 'table', 'X specific detail for a content item of kind x_post', 'One X post', 'signals', 'observed platform value', 'internal', 'active', null),
  ('signals', 'content_youtube_video', 'table', 'YouTube specific detail for a content item of kind youtube_video', 'One YouTube video', 'signals', 'observed platform value', 'internal', 'active', null),
  ('signals', 'dropdown_option', 'table', 'Operator editable select option used by the Signals interface', 'One option within a group', 'signals', 'app-owned', 'none', 'active', null),
  ('signals', 'github_account_detail', 'table', 'GitHub specific attributes of a tracked platform account', 'One GitHub account', 'signals', 'observed platform value', 'personal', 'active', null),
  ('signals', 'job_metric_kind', 'table', 'Controlled vocabulary of job counters, replacing sparse per-domain count columns', 'One counter definition', 'signals', 'app-owned', 'none', 'active', null),
  ('signals', 'job_request', 'table', 'Operator or scheduler request for background work, replacing six per-domain request tables', 'One requested job', 'signals', 'app-owned', 'internal', 'active', null),
  ('signals', 'job_run', 'table', 'Execution record of background work, replacing seven per-domain run tables', 'One job execution', 'signals', 'app-owned', 'internal', 'active', null),
  ('signals', 'job_run_metric', 'table', 'One counter value produced by one job run', 'One counter observation for one run', 'signals', 'source evidence', 'none', 'active', null),
  ('signals', 'linkedin_account_detail', 'table', 'LinkedIn specific attributes and rotation state of a tracked platform account', 'One LinkedIn account', 'signals', 'app-owned', 'personal', 'active', null),
  ('signals', 'linkedin_engagement_observation', 'table', 'Observed engagement by a tracked LinkedIn profile, used to detect activity for rotation banding', 'One observed engagement', 'signals', 'source evidence', 'personal', 'active', null),
  ('signals', 'major_analysis', 'table', 'Generated analysis panel for a featured publication, upserted per kind', 'One publication and analysis kind', 'signals', 'derived model output', 'internal', 'active', null),
  ('signals', 'major_publication', 'table', 'Publication featured in The Majors editorial surface', 'One featured publication', 'signals', 'app-owned', 'none', 'active', null),
  ('signals', 'platform_account', 'table', 'Observed account on an external platform, tracked independently of whether it is resolved to a canonical person', 'One account on one platform', 'signals', 'app-owned', 'personal', 'active', null),
  ('signals', 'pull_request_merge', 'table', 'Sampled pull request author and merger pair, the evidence behind the GitHub authority signal', 'One pull request', 'signals', 'source evidence', 'internal', 'active', null),
  ('signals', 'repo_contribution_week', 'table', 'Commits by one account to one repository in one week; the contribution fact grain', 'One account, repository and week', 'signals', 'source evidence', 'internal', 'active', null),
  ('signals', 'repo_contributor', 'table', 'Derived per contributor rollup of the weekly contribution grain, materialized for read performance', 'One account and repository', 'signals', 'derived model output', 'internal', 'active', null),
  ('signals', 'session_speaker', 'table', 'Participation of a speaker prospect in a conference session', 'One session and speaker', 'signals', 'source evidence', 'none', 'active', null),
  ('signals', 'signal_capture', 'table', 'Record that a content item satisfied a named signal preset', 'One preset and item', 'signals', 'source evidence', 'none', 'active', null),
  ('signals', 'speaker_list', 'table', 'Operator curated list of speaker prospects for outreach', 'One list', 'signals', 'app-owned', 'internal', 'active', null),
  ('signals', 'speaker_list_member', 'table', 'Membership of a speaker prospect in a curated outreach list', 'One list and prospect', 'signals', 'app-owned', 'personal', 'active', null),
  ('signals', 'speaker_profile', 'table', 'Scraped speaker prospect, linked to canonical identity only once confidently matched', 'One speaker prospect', 'signals', 'app-owned', 'personal', 'active', null),
  ('signals', 'tag', 'table', 'Signals working tag vocabulary, promoted to the governed taxonomy by review rather than automatically', 'One working tag', 'signals', 'app-owned', 'none', 'active', null),
  ('signals', 'tag_alias', 'table', 'Raw extracted string that resolves to a working tag', 'One alias string', 'signals', 'source evidence', 'none', 'active', null),
  ('signals', 'tag_cooccurrence', 'table', 'Derived count of an unordered tag pair appearing together, stored once per pair', 'One unordered tag pair', 'signals', 'derived model output', 'none', 'active', null),
  ('signals', 'tag_daily_stat', 'table', 'Derived daily coverage and sentiment rollup for a working tag', 'One tag and day', 'signals', 'derived model output', 'none', 'active', null),
  ('signals', 'tag_merge_suggestion', 'table', 'Proposed merge of two working tags awaiting human review', 'One proposed merge', 'signals', 'derived model output', 'none', 'active', null),
  ('signals', 'x_account_detail', 'table', 'X specific attributes of a tracked platform account', 'One X account', 'signals', 'observed platform value', 'internal', 'active', null),
  ('signals', 'x_bookmark', 'table', 'Operator bookmarked post', 'One bookmarked content item', 'signals', 'app-owned', 'internal', 'active', null),
  ('signals', 'x_list', 'table', 'Curated X list tracked for membership and timeline sweeps', 'One X list', 'signals', 'app-owned', 'internal', 'active', null),
  ('signals', 'x_list_member', 'table', 'Membership of an account in a tracked X list', 'One list and account', 'signals', 'observed platform value', 'personal', 'active', null),
  ('signals', 'youtube_channel_detail', 'table', 'YouTube specific attributes of a tracked platform account', 'One YouTube channel', 'signals', 'observed platform value', 'internal', 'active', null)
on conflict (schema_name, object_name) do update set
  purpose = excluded.purpose,
  row_grain = excluded.row_grain,
  owning_domain = excluded.owning_domain,
  authority = excluded.authority,
  pii_class = excluded.pii_class,
  lifecycle_state = excluded.lifecycle_state;

insert into meta.column_annotation
  (schema_name, table_name, column_name, meaning, authority,
   null_meaning, unit, pii_class, is_derived)
values
  ('signals', 'account_metric', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'account_metric', 'platform_account_id', 'Tracked platform account this row describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'account_metric', 'kind', 'Which account level metric this observation records', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'account_metric', 'value', 'Observed metric value at observed_at', 'source evidence', null, 'count', 'none', false),
  ('signals', 'account_metric', 'observed_at', 'Instant the metric was observed', 'source evidence', null, null, 'none', false),
  ('signals', 'account_metric', 'source_system', 'Originating system code from public.source_system', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Provenance not recorded', null, 'none', false),
  ('signals', 'account_score', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'account_score', 'platform_account_id', 'Account this score describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'personal', false),
  ('signals', 'account_score', 'score', 'Composite account score', 'derived model output', null, 'score', 'none', true),
  ('signals', 'account_score', 'reach', 'Reach component of the composite score', 'derived model output', 'Component not computed', 'score', 'none', true),
  ('signals', 'account_score', 'engagement', 'Engagement component of the composite score', 'derived model output', 'Component not computed', 'score', 'none', true),
  ('signals', 'account_score', 'curation', 'Curation component of the composite score', 'derived model output', 'Component not computed', 'score', 'none', true),
  ('signals', 'account_score', 'cadence', 'Posting cadence component of the composite score', 'derived model output', 'Component not computed', 'score', 'none', true),
  ('signals', 'account_score', 'components', 'Retained inputs and weights behind this score, kept so a historical score stays explainable', 'derived model output', null, null, 'internal', true),
  ('signals', 'account_score', 'scored_at', 'Instant the score was computed', 'derived model output', null, null, 'none', true),
  ('signals', 'account_score', 'model_version', 'Version of the scoring model that produced this score', 'derived model output', 'Model version not recorded', null, 'none', true),
  ('signals', 'conference', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'conference', 'slug', 'Stable identifier for the conference edition', 'app-owned', null, null, 'none', false),
  ('signals', 'conference', 'name', 'Conference name', 'source evidence', null, null, 'none', false),
  ('signals', 'conference', 'edition', 'Edition label such as a year or series marker', 'source evidence', 'Not labelled', null, 'none', false),
  ('signals', 'conference', 'starts_on', 'First day of the conference', 'source evidence', 'Dates not published', null, 'none', false),
  ('signals', 'conference', 'ends_on', 'Last day of the conference', 'source evidence', 'Dates not published', null, 'none', false),
  ('signals', 'conference', 'source_url', 'Page the programme was collected from', 'source evidence', 'Not recorded', null, 'none', false),
  ('signals', 'conference', 'created_at', 'Row creation timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'conference_session', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'conference_session', 'conference_id', 'Conference this session belongs to', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'conference_session', 'title', 'Session title as published', 'source evidence', null, null, 'none', false),
  ('signals', 'conference_session', 'abstract', 'Session abstract as published', 'source evidence', 'Not published', null, 'internal', false),
  ('signals', 'conference_session', 'session_date', 'Day the session took place', 'source evidence', 'Not published', null, 'none', false),
  ('signals', 'conference_session', 'track', 'Programme track containing the session', 'source evidence', 'Not tracked', null, 'none', false),
  ('signals', 'conference_session', 'source_url', 'Page the session was collected from', 'source evidence', 'Not recorded', null, 'none', false),
  ('signals', 'content_cluster', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'content_cluster', 'preset', 'Named signal preset the cluster was generated for', 'app-owned', null, null, 'none', false),
  ('signals', 'content_cluster', 'label', 'Generated cluster label', 'derived model output', null, null, 'none', true),
  ('signals', 'content_cluster', 'summary', 'Generated cluster summary', 'derived model output', 'Not summarized', null, 'internal', true),
  ('signals', 'content_cluster', 'built_at', 'Instant the cluster was generated', 'derived model output', null, null, 'none', true),
  ('signals', 'content_cluster', 'top_engagement', 'Highest engagement value among clustered items', 'derived model output', 'Not computed', 'count', 'none', true),
  ('signals', 'content_cluster_member', 'content_cluster_id', 'Cluster the item belongs to', 'derived model output', null, null, 'none', true),
  ('signals', 'content_cluster_member', 'content_item_id', 'Clustered content item', 'derived model output', null, null, 'none', true),
  ('signals', 'content_cluster_member', 'rank', 'Ordering of the item within the cluster', 'derived model output', 'Unranked', 'rank', 'none', true),
  ('signals', 'content_github_repo', 'content_item_id', 'Content item this row describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'content_github_repo', 'repo_id', 'Platform assigned repository identifier', 'observed platform value', null, null, 'none', false),
  ('signals', 'content_github_repo', 'owner_login', 'Repository owner login as observed', 'observed platform value', null, null, 'personal', false),
  ('signals', 'content_github_repo', 'repo_name', 'Repository name without the owner prefix', 'observed platform value', null, null, 'none', false),
  ('signals', 'content_github_repo', 'owner_account_id', 'Tracked account that owns the repository', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Owner not tracked or not yet resolved', null, 'personal', false),
  ('signals', 'content_github_repo', 'company_id', 'Canonical public.company that owns the repository', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Repository is not corporately owned, or is not yet resolved', null, 'none', false),
  ('signals', 'content_github_repo', 'primary_language', 'Dominant programming language reported by the platform', 'observed platform value', 'Not reported', null, 'none', false),
  ('signals', 'content_github_repo', 'license', 'Declared license identifier', 'observed platform value', 'No license declared', null, 'none', false),
  ('signals', 'content_github_repo', 'homepage', 'Project homepage URL', 'observed platform value', 'Not published', null, 'none', false),
  ('signals', 'content_github_repo', 'size_kb', 'Repository size reported by the platform', 'observed platform value', 'Not captured', 'kilobytes', 'none', false),
  ('signals', 'content_github_repo', 'is_archived', 'Whether the platform marks the repository archived', 'observed platform value', 'Archive state unknown', null, 'none', false),
  ('signals', 'content_github_repo', 'is_monitored', 'Whether Signals actively tracks this repository', 'app-owned', null, null, 'none', false),
  ('signals', 'content_github_repo', 'repo_created_at', 'Instant the repository was created', 'observed platform value', 'Not captured', null, 'none', false),
  ('signals', 'content_github_repo', 'pushed_at', 'Instant of the most recent push', 'observed platform value', 'Not captured', null, 'none', false),
  ('signals', 'content_github_repo', 'last_release_at', 'Instant of the most recent release', 'observed platform value', 'No release found', null, 'none', false),
  ('signals', 'content_github_repo', 'metrics_fetched_at', 'Instant repository metrics were last refreshed', 'app-owned', 'Never fetched', null, 'none', false),
  ('signals', 'content_linkedin_post', 'content_item_id', 'Content item this row describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'content_linkedin_post', 'post_urn', 'LinkedIn assigned post identifier', 'observed platform value', null, null, 'none', false),
  ('signals', 'content_linkedin_post', 'author_account_id', 'Tracked account that authored the post', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Author not tracked or not yet resolved', null, 'personal', false),
  ('signals', 'content_linkedin_post', 'is_repost', 'Whether the post is a repost', 'observed platform value', null, null, 'none', false),
  ('signals', 'content_linkedin_post', 'is_quote', 'Whether the post quotes another post', 'observed platform value', null, null, 'none', false),
  ('signals', 'content_linkedin_post', 'ingested_at', 'Instant the post was ingested', 'app-owned', null, null, 'none', false),
  ('signals', 'content_x_post', 'content_item_id', 'Content item this row describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'content_x_post', 'tweet_id', 'Platform assigned post identifier', 'observed platform value', null, null, 'none', false),
  ('signals', 'content_x_post', 'conversation_id', 'Identifier of the conversation thread containing the post', 'observed platform value', 'Not captured', null, 'none', false),
  ('signals', 'content_x_post', 'author_account_id', 'Tracked account that authored the post', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Author account not tracked or not yet resolved', null, 'personal', false),
  ('signals', 'content_x_post', 'is_reply', 'Whether the post replies to another post', 'observed platform value', null, null, 'none', false),
  ('signals', 'content_x_post', 'is_quote', 'Whether the post quotes another post', 'observed platform value', null, null, 'none', false),
  ('signals', 'content_x_post', 'is_repost', 'Whether the post is a repost of another post', 'observed platform value', null, null, 'none', false),
  ('signals', 'content_x_post', 'entities', 'Platform supplied entity annotations such as mentions and links', 'source evidence', 'No annotations supplied', null, 'internal', false),
  ('signals', 'content_x_post', 'referenced', 'Platform supplied references to other posts', 'source evidence', 'No references supplied', null, 'internal', false),
  ('signals', 'content_x_post', 'synced_at', 'Instant post fields were last refreshed', 'app-owned', 'Never refreshed', null, 'none', false),
  ('signals', 'content_youtube_video', 'content_item_id', 'Content item this row describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'content_youtube_video', 'video_id', 'Platform assigned video identifier', 'observed platform value', null, null, 'none', false),
  ('signals', 'content_youtube_video', 'channel_account_id', 'Tracked channel account that published the video', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Channel not tracked or not yet resolved', null, 'none', false),
  ('signals', 'content_youtube_video', 'duration_seconds', 'Video duration', 'observed platform value', 'Duration not captured', 'seconds', 'none', false),
  ('signals', 'content_youtube_video', 'is_short', 'Whether the video is a Short', 'derived model output', 'Format not determined', null, 'none', true),
  ('signals', 'content_youtube_video', 'thumbnail_url', 'Thumbnail image URL', 'observed platform value', 'Not captured', null, 'none', false),
  ('signals', 'content_youtube_video', 'published_text', 'Relative publication string exactly as scraped, such as two weeks ago', 'source evidence', 'Not scraped', null, 'internal', false),
  ('signals', 'content_youtube_video', 'is_published_estimated', 'Whether published_at was derived from a relative string rather than an exact timestamp', 'derived model output', null, null, 'none', true),
  ('signals', 'content_youtube_video', 'ingest_depth', 'How deeply the channel was walked when this video was found', 'app-owned', 'Not recorded', null, 'none', false),
  ('signals', 'content_youtube_video', 'ingested_at', 'Instant the video was ingested', 'app-owned', null, null, 'none', false),
  ('signals', 'dropdown_option', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'dropdown_option', 'group_code', 'Option group this value belongs to', 'app-owned', null, null, 'none', false),
  ('signals', 'dropdown_option', 'value', 'Stored value submitted by the interface', 'app-owned', null, null, 'none', false),
  ('signals', 'dropdown_option', 'label', 'Label shown to the operator', 'app-owned', null, null, 'none', false),
  ('signals', 'dropdown_option', 'position', 'Ordering position within the group', 'app-owned', null, 'rank', 'none', false),
  ('signals', 'dropdown_option', 'is_active', 'Whether the option is currently offered', 'app-owned', null, null, 'none', false),
  ('signals', 'dropdown_option', 'created_at', 'Row creation timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'github_account_detail', 'platform_account_id', 'Tracked platform account this row describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'github_account_detail', 'account_type', 'Whether the GitHub account is a user or an organization', 'observed platform value', 'Not determined', null, 'none', false),
  ('signals', 'github_account_detail', 'actor_class', 'Classification of the account as human, bot or agent', 'derived model output', 'Not classified', null, 'none', true),
  ('signals', 'github_account_detail', 'agent_vendor', 'Vendor of the coding agent when the account is an agent', 'derived model output', 'Not an agent account', null, 'none', true),
  ('signals', 'github_account_detail', 'company_raw', 'Employer string exactly as self reported on the profile', 'observed platform value', 'Not published', null, 'personal', false),
  ('signals', 'github_account_detail', 'company_norm', 'Case and punctuation folded employer string used for matching', 'derived model output', 'No employer to normalize', null, 'personal', true),
  ('signals', 'github_account_detail', 'company_id', 'Canonical public.company matched from the self reported employer', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Employer absent or not yet resolved to a canonical company', null, 'none', false),
  ('signals', 'github_account_detail', 'email', 'Public profile email address', 'observed platform value', 'Not published', null, 'personal', false),
  ('signals', 'github_account_detail', 'blog', 'Personal site URL from the profile', 'observed platform value', 'Not published', null, 'none', false),
  ('signals', 'github_account_detail', 'public_repos', 'Count of public repositories at last sync', 'observed platform value', 'Not captured', 'repositories', 'none', false),
  ('signals', 'github_account_detail', 'profile_fetched_at', 'Instant GitHub profile fields were last refreshed', 'app-owned', 'Never fetched', null, 'none', false),
  ('signals', 'job_metric_kind', 'code', 'Stable counter code referenced by job run metrics', 'app-owned', null, null, 'none', false),
  ('signals', 'job_metric_kind', 'label', 'Human readable counter name', 'app-owned', null, null, 'none', false),
  ('signals', 'job_metric_kind', 'unit', 'Unit the counter is expressed in', 'app-owned', 'Dimensionless count', null, 'none', false),
  ('signals', 'job_metric_kind', 'description', 'What the counter measures', 'app-owned', 'Not described', null, 'none', false),
  ('signals', 'job_request', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'job_request', 'kind', 'Which kind of background work was requested', 'app-owned', null, null, 'none', false),
  ('signals', 'job_request', 'status', 'Lifecycle state of the request', 'app-owned', null, null, 'none', false),
  ('signals', 'job_request', 'params', 'Request parameters supplied by the caller', 'app-owned', 'No parameters supplied', null, 'internal', false),
  ('signals', 'job_request', 'requested_at', 'Instant the work was requested', 'app-owned', null, null, 'none', false),
  ('signals', 'job_request', 'requested_by', 'Identifier of the operator or scheduler that requested the work', 'app-owned', 'Requester not recorded', null, 'internal', false),
  ('signals', 'job_request', 'started_at', 'Instant a worker claimed the request', 'app-owned', 'Not yet claimed', null, 'none', false),
  ('signals', 'job_request', 'finished_at', 'Instant the request reached a terminal state', 'app-owned', 'Still pending or running', null, 'none', false),
  ('signals', 'job_request', 'summary', 'Structured outcome reported by the worker', 'app-owned', 'No outcome recorded yet', null, 'internal', false),
  ('signals', 'job_request', 'error', 'Failure cause when the request failed', 'app-owned', 'Request did not fail', null, 'internal', false),
  ('signals', 'job_request', 'run_id', 'Execution that fulfilled this request', 'app-owned', 'Not yet executed', null, 'none', false),
  ('signals', 'job_run', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'job_run', 'kind', 'Which kind of background work executed', 'app-owned', null, null, 'none', false),
  ('signals', 'job_run', 'status', 'Lifecycle state of the execution', 'app-owned', null, null, 'none', false),
  ('signals', 'job_run', 'job_request_id', 'Request that triggered this execution', 'app-owned', 'Execution was scheduled rather than requested by an operator', null, 'none', false),
  ('signals', 'job_run', 'started_at', 'Instant execution began', 'app-owned', null, null, 'none', false),
  ('signals', 'job_run', 'finished_at', 'Instant execution reached a terminal state', 'app-owned', 'Still running', null, 'none', false),
  ('signals', 'job_run', 'api_calls', 'Number of external API calls made', 'source evidence', 'Not counted', 'calls', 'none', false),
  ('signals', 'job_run', 'est_cost_usd', 'Estimated external API cost of this execution', 'derived model output', 'Not estimated', 'USD', 'none', true),
  ('signals', 'job_run', 'params', 'Effective parameters used by the execution', 'app-owned', 'No parameters', null, 'internal', false),
  ('signals', 'job_run', 'summary', 'Structured outcome reported by the execution', 'app-owned', 'No outcome recorded', null, 'internal', false),
  ('signals', 'job_run', 'error', 'Failure cause when the execution failed', 'app-owned', 'Execution did not fail', null, 'internal', false),
  ('signals', 'job_run_metric', 'job_run_id', 'Execution that produced this counter', 'app-owned', null, null, 'none', false),
  ('signals', 'job_run_metric', 'metric_code', 'Which counter this value records', 'app-owned', null, null, 'none', false),
  ('signals', 'job_run_metric', 'value', 'Counter value for this execution', 'source evidence', null, 'count', 'none', false),
  ('signals', 'linkedin_account_detail', 'platform_account_id', 'Tracked platform account this row describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'linkedin_account_detail', 'slug', 'Public profile slug from the LinkedIn URL', 'observed platform value', 'Not captured', null, 'personal', false),
  ('signals', 'linkedin_account_detail', 'headline', 'Profile headline as observed', 'observed platform value', 'Not published', null, 'personal', false),
  ('signals', 'linkedin_account_detail', 'band', 'Rotation band controlling sweep frequency', 'app-owned', 'Not banded', null, 'none', false),
  ('signals', 'linkedin_account_detail', 'score', 'Priority score used to order sweeps', 'derived model output', 'Not scored', null, 'none', true),
  ('signals', 'linkedin_account_detail', 'url_type', 'Whether the profile URL is a public vanity slug or an opaque identifier', 'observed platform value', 'Not classified', null, 'none', false),
  ('signals', 'linkedin_account_detail', 'source', 'How this profile entered the roster', 'app-owned', 'Not recorded', null, 'none', false),
  ('signals', 'linkedin_account_detail', 'is_pinned', 'Whether the operator pinned this profile into every sweep', 'app-owned', null, null, 'none', false),
  ('signals', 'linkedin_account_detail', 'is_probation', 'Whether the profile is on probation for repeatedly returning no result', 'app-owned', null, null, 'none', false),
  ('signals', 'linkedin_account_detail', 'is_self_confirmed', 'Whether the profile was confirmed by the person themselves', 'app-owned', null, null, 'none', false),
  ('signals', 'linkedin_account_detail', 'cooldown_until', 'Instant before which this profile must not be swept again', 'app-owned', 'No cooldown in force', null, 'none', false),
  ('signals', 'linkedin_account_detail', 'last_swept_at', 'Instant this profile was last swept', 'app-owned', 'Never swept', null, 'none', false),
  ('signals', 'linkedin_account_detail', 'last_authored_at', 'Publication instant of the most recent authored post found', 'observed platform value', 'No authored post found', null, 'none', false),
  ('signals', 'linkedin_account_detail', 'notes', 'Operator note about the profile', 'app-owned', 'No note', null, 'internal', false),
  ('signals', 'linkedin_engagement_observation', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'linkedin_engagement_observation', 'content_item_id', 'Post that was engaged with', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Engaged post is not ingested as a content item', null, 'none', false),
  ('signals', 'linkedin_engagement_observation', 'platform_account_id', 'Tracked profile that engaged', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'personal', false),
  ('signals', 'linkedin_engagement_observation', 'post_urn', 'LinkedIn identifier of the engaged post', 'observed platform value', 'Not captured', null, 'none', false),
  ('signals', 'linkedin_engagement_observation', 'posted_at', 'Publication instant of the engaged post', 'observed platform value', 'Not captured', null, 'none', false),
  ('signals', 'linkedin_engagement_observation', 'observed_at', 'Instant the engagement was observed', 'source evidence', null, null, 'none', false),
  ('signals', 'major_analysis', 'major_publication_id', 'Featured publication this analysis describes', 'app-owned', null, null, 'none', false),
  ('signals', 'major_analysis', 'kind', 'Which analysis panel this payload populates', 'app-owned', null, null, 'none', false),
  ('signals', 'major_analysis', 'payload', 'Generated analysis content for the panel', 'derived model output', null, null, 'internal', true),
  ('signals', 'major_analysis', 'generated_at', 'Instant the analysis was generated', 'derived model output', null, null, 'none', true),
  ('signals', 'major_analysis', 'model_version', 'Model that produced the analysis', 'derived model output', 'Not recorded', null, 'none', true),
  ('signals', 'major_publication', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'major_publication', 'slug', 'Stable identifier for the featured publication', 'app-owned', null, null, 'none', false),
  ('signals', 'major_publication', 'name', 'Display name of the publication', 'app-owned', null, null, 'none', false),
  ('signals', 'major_publication', 'view_type', 'Which custom analysis panel renders for this publication; the standard article feed renders regardless', 'app-owned', null, null, 'none', false),
  ('signals', 'major_publication', 'content_source_id', 'Canonical content channel this publication corresponds to', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Not linked to an ingested channel', null, 'none', false),
  ('signals', 'major_publication', 'is_active', 'Whether the publication is currently featured', 'app-owned', null, null, 'none', false),
  ('signals', 'major_publication', 'position', 'Ordering position in The Majors index', 'app-owned', 'Unordered', 'rank', 'none', false),
  ('signals', 'major_publication', 'created_at', 'Row creation timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'major_publication', 'updated_at', 'Last modification timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'platform_account', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'platform_account', 'platform', 'External platform the account exists on', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'platform_account', 'handle', 'Handle exactly as observed on the platform', 'observed platform value', null, null, 'personal', false),
  ('signals', 'platform_account', 'normalized_handle', 'Lowercased handle with any URL wrapper removed; the display identity deduplication key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'personal', true),
  ('signals', 'platform_account', 'platform_account_id', 'Stable numeric or opaque identifier assigned by the platform, which survives a rename', 'observed platform value', 'Platform identifier not captured, so only the handle identifies this account', null, 'personal', false),
  ('signals', 'platform_account', 'display_name', 'Profile display name as observed', 'observed platform value', 'Not published', null, 'personal', false),
  ('signals', 'platform_account', 'description', 'Profile biography as observed', 'observed platform value', 'Not published', null, 'personal', false),
  ('signals', 'platform_account', 'url', 'Canonical profile URL on the platform', 'observed platform value', 'Not captured', null, 'none', false),
  ('signals', 'platform_account', 'avatar_url', 'Profile image URL as observed', 'observed platform value', 'Not captured', null, 'none', false),
  ('signals', 'platform_account', 'location', 'Self reported location as observed', 'observed platform value', 'Not published', null, 'personal', false),
  ('signals', 'platform_account', 'is_verified', 'Whether the platform marks the account verified', 'observed platform value', 'Verification state unknown', null, 'none', false),
  ('signals', 'platform_account', 'account_created_at', 'Instant the account was created on the platform', 'observed platform value', 'Not published', null, 'none', false),
  ('signals', 'platform_account', 'person_id', 'Canonical public.person this account belongs to', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Account is not yet resolved to a canonical person, which is the normal initial state', null, 'personal', false),
  ('signals', 'platform_account', 'person_handle_id', 'Governed public.person_handle row mirroring this account once it is resolved', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Account has no governed handle row, because it is unresolved or unpromoted', null, 'personal', false),
  ('signals', 'platform_account', 'first_seen_at', 'Instant this account was first observed by Signals', 'app-owned', null, null, 'none', false),
  ('signals', 'platform_account', 'last_synced_at', 'Instant the profile was last refreshed from the platform', 'app-owned', 'Never synced', null, 'none', false),
  ('signals', 'platform_account', 'is_monitored', 'Whether Signals actively ingests this account', 'app-owned', null, null, 'none', false),
  ('signals', 'platform_account', 'source_system', 'Originating system code from public.source_system', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Provenance not recorded', null, 'none', false),
  ('signals', 'platform_account', 'raw', 'Retained source payload for this row', 'source evidence', null, null, 'internal', false),
  ('signals', 'platform_account', 'created_at', 'Row creation timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'platform_account', 'updated_at', 'Last modification timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'pull_request_merge', 'content_item_id', 'Repository the pull request belongs to', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'pull_request_merge', 'pr_number', 'Pull request number within the repository', 'observed platform value', null, null, 'none', false),
  ('signals', 'pull_request_merge', 'author_account_id', 'Account that authored the pull request', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Author not tracked or not yet resolved', null, 'personal', false),
  ('signals', 'pull_request_merge', 'merged_by_account_id', 'Account that merged the pull request', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Not merged, or merger not tracked', null, 'personal', false),
  ('signals', 'pull_request_merge', 'merged_at', 'Instant the pull request was merged', 'observed platform value', 'Not merged', null, 'none', false),
  ('signals', 'pull_request_merge', 'sampled_at', 'Instant this pull request was sampled', 'app-owned', null, null, 'none', false),
  ('signals', 'repo_contribution_week', 'content_item_id', 'Repository the commits were made to', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'repo_contribution_week', 'platform_account_id', 'Account credited with the commits', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'personal', false),
  ('signals', 'repo_contribution_week', 'week_starting', 'Sunday beginning the weekly bucket reported by the platform', 'source evidence', null, null, 'none', false),
  ('signals', 'repo_contribution_week', 'commits', 'Commits credited in this week', 'source evidence', null, 'commits', 'none', false),
  ('signals', 'repo_contributor', 'content_item_id', 'Repository this rollup describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'repo_contributor', 'platform_account_id', 'Account this rollup describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'personal', false),
  ('signals', 'repo_contributor', 'commits_total', 'Total commits across all known weeks', 'derived model output', null, 'commits', 'none', true),
  ('signals', 'repo_contributor', 'commits_365d', 'Commits in the trailing 365 days', 'derived model output', null, 'commits', 'none', true),
  ('signals', 'repo_contributor', 'commits_90d', 'Commits in the trailing 90 days', 'derived model output', null, 'commits', 'none', true),
  ('signals', 'repo_contributor', 'weeks_active', 'Number of weeks with at least one commit', 'derived model output', null, 'weeks', 'none', true),
  ('signals', 'repo_contributor', 'first_commit_week', 'Earliest week with a commit', 'derived model output', 'No commits recorded', null, 'none', true),
  ('signals', 'repo_contributor', 'last_commit_week', 'Most recent week with a commit', 'derived model output', 'No commits recorded', null, 'none', true),
  ('signals', 'repo_contributor', 'share_total', 'Share of all repository commits attributable to this account', 'derived model output', 'Not computed', 'fraction 0-1', 'none', true),
  ('signals', 'repo_contributor', 'share_90d', 'Share of trailing 90 day repository commits attributable to this account', 'derived model output', 'Not computed', 'fraction 0-1', 'none', true),
  ('signals', 'repo_contributor', 'rank_commits', 'Rank of this account among repository contributors by commits', 'derived model output', 'Not ranked', 'rank', 'none', true),
  ('signals', 'repo_contributor', 'is_top10', 'Whether the account is among the ten leading contributors', 'derived model output', null, null, 'none', true),
  ('signals', 'repo_contributor', 'importance', 'Composite contributor importance measure', 'derived model output', 'Not computed', null, 'none', true),
  ('signals', 'repo_contributor', 'prs_authored', 'Pull requests authored by this account in the sampled window', 'source evidence', 'Not sampled', 'pull requests', 'none', false),
  ('signals', 'repo_contributor', 'prs_merged', 'Pull requests authored by this account that were merged', 'source evidence', 'Not sampled', 'pull requests', 'none', false),
  ('signals', 'repo_contributor', 'merges_performed', 'Pull requests this account merged for others', 'source evidence', 'Not sampled', 'pull requests', 'none', false),
  ('signals', 'repo_contributor', 'computed_at', 'Timestamp the derived values were last rebuilt', 'derived model output', null, null, 'none', true),
  ('signals', 'session_speaker', 'conference_session_id', 'Session that was presented', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'session_speaker', 'speaker_profile_id', 'Speaker prospect who presented', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'personal', false),
  ('signals', 'session_speaker', 'speaker_role', 'Role the speaker held in the session', 'source evidence', 'Role not distinguished', null, 'none', false),
  ('signals', 'signal_capture', 'preset', 'Named signal preset that matched', 'app-owned', null, null, 'none', false),
  ('signals', 'signal_capture', 'content_item_id', 'Content item that satisfied the preset', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'signal_capture', 'fetched_at', 'Instant the match was recorded', 'source evidence', null, null, 'none', false),
  ('signals', 'speaker_list', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'speaker_list', 'slug', 'Stable identifier for the outreach list', 'app-owned', null, null, 'none', false),
  ('signals', 'speaker_list', 'name', 'List name', 'app-owned', null, null, 'none', false),
  ('signals', 'speaker_list', 'description', 'What the list is for', 'app-owned', 'Not described', null, 'internal', false),
  ('signals', 'speaker_list', 'created_at', 'Row creation timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'speaker_list_member', 'speaker_list_id', 'Outreach list the prospect belongs to', 'app-owned', null, null, 'none', false),
  ('signals', 'speaker_list_member', 'speaker_profile_id', 'Speaker prospect on the list', 'app-owned', null, null, 'personal', false),
  ('signals', 'speaker_list_member', 'position', 'Ordering position in the list', 'app-owned', 'Unordered', 'rank', 'none', false),
  ('signals', 'speaker_list_member', 'note', 'Operator note about this prospect on this list', 'app-owned', 'No note', null, 'internal', false),
  ('signals', 'speaker_list_member', 'added_at', 'Instant the prospect was added to the list', 'app-owned', null, null, 'none', false),
  ('signals', 'speaker_profile', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'speaker_profile', 'full_name', 'Speaker name exactly as published in the programme', 'source evidence', null, null, 'personal', false),
  ('signals', 'speaker_profile', 'title', 'Job title as published', 'source evidence', 'Not published', null, 'personal', false),
  ('signals', 'speaker_profile', 'bio', 'Speaker biography as published', 'source evidence', 'Not published', null, 'personal', false),
  ('signals', 'speaker_profile', 'person_id', 'Canonical public.person this prospect was matched to', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Prospect is unmatched, so no canonical person record is implied', null, 'personal', false),
  ('signals', 'speaker_profile', 'company_id', 'Canonical public.company this prospect was matched to', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Employer unmatched or not published', null, 'none', false),
  ('signals', 'speaker_profile', 'company_raw', 'Employer string exactly as published in the programme', 'source evidence', 'Not published', null, 'personal', false),
  ('signals', 'speaker_profile', 'archetype', 'Assigned editorial archetype of strategist, architect or engineer', 'derived model output', 'Not yet assigned', null, 'none', true),
  ('signals', 'speaker_profile', 'influence_score', 'Composite prospect influence measure', 'derived model output', 'Not scored', 'score 0-100', 'none', true),
  ('signals', 'speaker_profile', 'x_account_id', 'Tracked X account belonging to this prospect', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'No X account found or confirmed', null, 'personal', false),
  ('signals', 'speaker_profile', 'linkedin_account_id', 'Tracked LinkedIn account belonging to this prospect', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'No LinkedIn account found or confirmed', null, 'personal', false),
  ('signals', 'speaker_profile', 'source_url', 'Programme page this prospect was collected from', 'source evidence', 'Not recorded', null, 'none', false),
  ('signals', 'speaker_profile', 'created_at', 'Row creation timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'speaker_profile', 'updated_at', 'Last modification timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'tag', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'tag', 'slug', 'Stable lowercase identifier for the working tag', 'app-owned', null, null, 'none', false),
  ('signals', 'tag', 'display_name', 'Human readable tag label', 'app-owned', null, null, 'none', false),
  ('signals', 'tag', 'description', 'Editorial description of the tag', 'app-owned', 'Not described', null, 'internal', false),
  ('signals', 'tag', 'color', 'Display colour for the tag', 'app-owned', 'No colour assigned', null, 'none', false),
  ('signals', 'tag', 'parent_id', 'Broader working tag containing this one', 'app-owned', 'Tag is a root of the hierarchy', null, 'none', false),
  ('signals', 'tag', 'canonical_tag_id', 'Governed public.tag this working tag has been promoted to', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Working tag has not been promoted to the governed taxonomy', null, 'none', false),
  ('signals', 'tag', 'is_curated', 'Whether a human has reviewed this tag', 'app-owned', null, null, 'none', false),
  ('signals', 'tag', 'created_at', 'Row creation timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'tag', 'updated_at', 'Last modification timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'tag_alias', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'tag_alias', 'tag_id', 'Working tag this alias resolves to', 'app-owned', null, null, 'none', false),
  ('signals', 'tag_alias', 'raw_alias', 'Alias string exactly as extracted', 'source evidence', null, null, 'none', false),
  ('signals', 'tag_alias', 'normalized_alias', 'Lowercased alias with separators unified and punctuation removed; the global resolution key', 'derived model output', null, null, 'none', true),
  ('signals', 'tag_alias', 'confidence', 'Model confidence that the alias resolves to this tag', 'derived model output', 'Alias was asserted by a human rather than scored', 'fraction 0-1', 'none', true),
  ('signals', 'tag_alias', 'source_system', 'Originating system code from public.source_system', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Provenance not recorded', null, 'none', false),
  ('signals', 'tag_alias', 'created_at', 'Row creation timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'tag_cooccurrence', 'tag_a', 'Lower ordered tag of the pair; the ordering is enforced so a pair has one row', 'derived model output', null, null, 'none', true),
  ('signals', 'tag_cooccurrence', 'tag_b', 'Higher ordered tag of the pair', 'derived model output', null, null, 'none', true),
  ('signals', 'tag_cooccurrence', 'cooccurrences', 'Content items carrying both tags', 'derived model output', null, 'items', 'none', true),
  ('signals', 'tag_cooccurrence', 'last_seen_at', 'Instant the pair was most recently seen together', 'derived model output', 'Not recorded', null, 'none', true),
  ('signals', 'tag_cooccurrence', 'computed_at', 'Timestamp the derived values were last rebuilt', 'derived model output', null, null, 'none', true),
  ('signals', 'tag_daily_stat', 'tag_id', 'Working tag this rollup describes', 'app-owned', null, null, 'none', false),
  ('signals', 'tag_daily_stat', 'day', 'Calendar day the rollup covers', 'derived model output', null, null, 'none', true),
  ('signals', 'tag_daily_stat', 'article_count', 'Content items carrying this tag on this day', 'derived model output', null, 'items', 'none', true),
  ('signals', 'tag_daily_stat', 'avg_importance', 'Mean importance score of those items', 'derived model output', 'No items that day', 'score 0-100', 'none', true),
  ('signals', 'tag_daily_stat', 'sentiment_pos', 'Items classified positive', 'derived model output', null, 'items', 'none', true),
  ('signals', 'tag_daily_stat', 'sentiment_neu', 'Items classified neutral', 'derived model output', null, 'items', 'none', true),
  ('signals', 'tag_daily_stat', 'sentiment_neg', 'Items classified negative', 'derived model output', null, 'items', 'none', true),
  ('signals', 'tag_daily_stat', 'computed_at', 'Timestamp the derived values were last rebuilt', 'derived model output', null, null, 'none', true),
  ('signals', 'tag_merge_suggestion', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'tag_merge_suggestion', 'from_tag_id', 'Working tag proposed to be absorbed', 'derived model output', null, null, 'none', true),
  ('signals', 'tag_merge_suggestion', 'into_tag_id', 'Working tag proposed to absorb the other', 'derived model output', null, null, 'none', true),
  ('signals', 'tag_merge_suggestion', 'reason', 'Explanation of why the merge was proposed', 'derived model output', 'No reason recorded', null, 'internal', true),
  ('signals', 'tag_merge_suggestion', 'score', 'Confidence that the two tags are the same concept', 'derived model output', 'Not scored', 'fraction 0-1', 'none', true),
  ('signals', 'tag_merge_suggestion', 'status', 'Review state of the suggestion', 'app-owned', null, null, 'none', false),
  ('signals', 'tag_merge_suggestion', 'created_at', 'Row creation timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'tag_merge_suggestion', 'decided_at', 'Instant a human decided the suggestion', 'app-owned', 'Still awaiting review', null, 'none', false),
  ('signals', 'x_account_detail', 'platform_account_id', 'Tracked platform account this row describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'x_account_detail', 'is_following', 'Whether the operator account follows this account', 'observed platform value', 'Follow state not checked', null, 'none', false),
  ('signals', 'x_account_detail', 'listed_count', 'Number of public lists containing this account', 'observed platform value', 'Not captured', 'lists', 'none', false),
  ('signals', 'x_account_detail', 'categories', 'Platform assigned professional categories', 'observed platform value', 'None assigned', null, 'none', false),
  ('signals', 'x_account_detail', 'profile_synced_at', 'Instant X profile fields were last refreshed', 'app-owned', 'Never synced', null, 'none', false),
  ('signals', 'x_bookmark', 'content_item_id', 'Bookmarked content item', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'x_bookmark', 'position', 'Ordering position in the operator bookmark list', 'app-owned', 'Unordered', 'rank', 'none', false),
  ('signals', 'x_bookmark', 'synced_at', 'Instant the bookmark was last confirmed from the platform', 'app-owned', null, null, 'none', false),
  ('signals', 'x_list', 'id', 'Surrogate primary key', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'x_list', 'list_id', 'Platform assigned list identifier', 'observed platform value', null, null, 'none', false),
  ('signals', 'x_list', 'name', 'List name as observed', 'observed platform value', null, null, 'none', false),
  ('signals', 'x_list', 'description', 'List description as observed', 'observed platform value', 'Not published', null, 'internal', false),
  ('signals', 'x_list', 'owner_account_id', 'Tracked account that owns the list', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', 'Owner not tracked or not yet resolved', null, 'personal', false),
  ('signals', 'x_list', 'is_private', 'Whether the list is private on the platform', 'observed platform value', null, null, 'none', false),
  ('signals', 'x_list', 'list_created_at', 'Instant the list was created', 'observed platform value', 'Not captured', null, 'none', false),
  ('signals', 'x_list', 'members_synced_at', 'Instant list membership was last refreshed', 'app-owned', 'Never synced', null, 'none', false),
  ('signals', 'x_list', 'timeline_synced_at', 'Instant the list timeline was last swept', 'app-owned', 'Never swept', null, 'none', false),
  ('signals', 'x_list', 'created_at', 'Row creation timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'x_list', 'updated_at', 'Last modification timestamp in this database', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'x_list_member', 'x_list_id', 'List the account belongs to', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'x_list_member', 'platform_account_id', 'Account in the list', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'personal', false),
  ('signals', 'x_list_member', 'first_seen_at', 'Instant the account was first seen in the list', 'source evidence', null, null, 'none', false),
  ('signals', 'x_list_member', 'last_seen_at', 'Instant the account was most recently confirmed in the list', 'source evidence', 'Membership not reconfirmed since first observation', null, 'none', false),
  ('signals', 'youtube_channel_detail', 'platform_account_id', 'Tracked platform account this row describes', 'Typed canonical fact with retained source attribution; not an unqualified inferred truth', null, null, 'none', false),
  ('signals', 'youtube_channel_detail', 'playlist_id', 'Uploads playlist identifier used to enumerate videos', 'observed platform value', 'Not resolved', null, 'none', false),
  ('signals', 'youtube_channel_detail', 'beat', 'Editorial beat this channel is tracked under', 'app-owned', 'Not assigned', null, 'none', false),
  ('signals', 'youtube_channel_detail', 'list_name', 'Operator grouping label for the channel', 'app-owned', 'Not grouped', null, 'none', false),
  ('signals', 'youtube_channel_detail', 'source_kind', 'How the channel entered the tracking set', 'app-owned', 'Not recorded', null, 'none', false),
  ('signals', 'youtube_channel_detail', 'note', 'Operator note about the channel', 'app-owned', 'No note', null, 'internal', false),
  ('signals', 'youtube_channel_detail', 'last_video_at', 'Publication instant of the most recent known video', 'derived model output', 'No videos known', null, 'none', true),
  ('signals', 'youtube_channel_detail', 'first_ingested_at', 'Instant this channel was first ingested', 'app-owned', 'Never ingested', null, 'none', false),
  ('signals', 'youtube_channel_detail', 'last_ingested_at', 'Instant this channel was last ingested', 'app-owned', 'Never ingested', null, 'none', false)
on conflict (schema_name, table_name, column_name) do update set
  meaning = excluded.meaning,
  authority = excluded.authority,
  null_meaning = excluded.null_meaning,
  unit = excluded.unit,
  pii_class = excluded.pii_class,
  is_derived = excluded.is_derived;

-- Relations that may be referenced polymorphically by meta.source_binding.
insert into meta.binding_target(relation_name, id_column) values
  ('signals.platform_account', 'id'),
  ('signals.tag', 'id'),
  ('signals.speaker_profile', 'id'),
  ('signals.major_publication', 'id'),
  ('signals.job_run', 'id')
on conflict (relation_name) do nothing;

-- Signals runs server side under its own role. The browser never holds a
-- database credential. The application owns its private schema outright but
-- still only proposes canonical identity, which is why no contract row here
-- grants write on any public table.
insert into meta.app_contract
  (app_code, role_name, schema_name, object_name, access_kind, purpose, requires_audit, approved_at)
values
  ('idn_signals', 'idn_signals_app', 'signals', 'platform_account', 'write',
   'Server-only ingestion of observed platform accounts.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'x_account_detail', 'write',
   'Platform-specific account attributes.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'github_account_detail', 'write',
   'Platform-specific account attributes.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'youtube_channel_detail', 'write',
   'Platform-specific account attributes.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'linkedin_account_detail', 'write',
   'Platform-specific account attributes and rotation state.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'account_metric', 'write',
   'Append-only account metric observations.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'content_x_post', 'write',
   'Platform-specific content detail.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'content_youtube_video', 'write',
   'Platform-specific content detail.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'content_github_repo', 'write',
   'Platform-specific content detail.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'content_linkedin_post', 'write',
   'Platform-specific content detail.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'job_request', 'write',
   'Background work queue owned by the application.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'job_run', 'write',
   'Background work execution log owned by the application.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'job_run_metric', 'write',
   'Per-run counters owned by the application.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'repo_contribution_week', 'write',
   'Contribution grain ingestion.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'repo_contributor', 'write',
   'Derived contributor rollup rebuild.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'pull_request_merge', 'write',
   'Pull request authority sampling.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'tag', 'write',
   'Signals working tag vocabulary, distinct from the governed taxonomy.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'tag_alias', 'write',
   'Alias resolution for the working vocabulary.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'tag_daily_stat', 'write',
   'Derived tag rollups.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'tag_cooccurrence', 'write',
   'Derived tag pair rollups.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'tag_merge_suggestion', 'write',
   'Proposed tag merges awaiting review.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'x_list', 'write',
   'Curated X list tracking.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'x_list_member', 'write',
   'Curated X list membership.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'x_bookmark', 'write',
   'Operator bookmarks.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'content_cluster', 'write',
   'Generated topic clusters.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'content_cluster_member', 'write',
   'Generated cluster membership.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'signal_capture', 'write',
   'Signal preset match log.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'account_score', 'write',
   'Append-only account scoring history.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'linkedin_engagement_observation', 'write',
   'Observed LinkedIn engagement.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'conference', 'write',
   'Scraped conference programmes.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'speaker_profile', 'write',
   'Speaker prospects, which never write canonical identity.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'conference_session', 'write',
   'Scraped conference sessions.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'session_speaker', 'write',
   'Scraped session participation.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'speaker_list', 'write',
   'Operator outreach lists.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'speaker_list_member', 'write',
   'Operator outreach list membership.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'major_publication', 'write',
   'Editorial Majors configuration.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'major_analysis', 'write',
   'Generated Majors analysis panels.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'dropdown_option', 'write',
   'Operator-editable interface options.', true, now()),
  ('idn_signals', 'idn_signals_app', 'signals', 'job_metric_kind', 'read',
   'Controlled counter vocabulary is release-managed, not app-written.', true, now())
on conflict (app_code, role_name, schema_name, object_name, access_kind) do nothing;

commit;
