-- P8R1 / reconstructed proposal, NOT historical source. NOT APPLIED.
-- Run only in an explicitly authorized disposable rehearsal, inside one transaction.
SELECT pg_temp.p8r_guard();
SET LOCAL search_path = public, pg_catalog;

ALTER TABLE public."campaign_send" ADD COLUMN "clicks" "pg_catalog"."int4" DEFAULT 0 NOT NULL;
COMMENT ON COLUMN public."campaign_send"."clicks" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."campaign_send" ADD COLUMN "first_clicked_at" "pg_catalog"."timestamptz";
COMMENT ON COLUMN public."campaign_send"."first_clicked_at" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."campaign_send" ADD COLUMN "first_opened_at" "pg_catalog"."timestamptz";
COMMENT ON COLUMN public."campaign_send"."first_opened_at" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."campaign_send" ADD COLUMN "last_clicked_at" "pg_catalog"."timestamptz";
COMMENT ON COLUMN public."campaign_send"."last_clicked_at" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."campaign_send" ADD COLUMN "last_clicked_url" "pg_catalog"."text";
COMMENT ON COLUMN public."campaign_send"."last_clicked_url" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."campaign_send" ADD COLUMN "last_opened_at" "pg_catalog"."timestamptz";
COMMENT ON COLUMN public."campaign_send"."last_opened_at" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."campaign_send" ADD COLUMN "opens" "pg_catalog"."int4" DEFAULT 0 NOT NULL;
COMMENT ON COLUMN public."campaign_send"."opens" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."campaign_send" ADD COLUMN "provider_events" "pg_catalog"."jsonb" DEFAULT '[]'::jsonb NOT NULL;
COMMENT ON COLUMN public."campaign_send"."provider_events" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."campaign_send" ADD COLUMN "snapshot_id" "pg_catalog"."uuid";
COMMENT ON COLUMN public."campaign_send"."snapshot_id" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."campaign_send" ADD COLUMN "stubbed_html" "pg_catalog"."text";
COMMENT ON COLUMN public."campaign_send"."stubbed_html" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."campaign_send" ADD COLUMN "subject" "pg_catalog"."text";
COMMENT ON COLUMN public."campaign_send"."subject" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "activity" "pg_catalog"."text"[];
COMMENT ON COLUMN public."company"."activity" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "blockers_count" "pg_catalog"."int4" DEFAULT 0 NOT NULL;
COMMENT ON COLUMN public."company"."blockers_count" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "company_owner" "pg_catalog"."text";
COMMENT ON COLUMN public."company"."company_owner" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "conference_speaking" "pg_catalog"."text"[];
COMMENT ON COLUMN public."company"."conference_speaking" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "conferences" "pg_catalog"."text"[];
COMMENT ON COLUMN public."company"."conferences" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "group" "pg_catalog"."text";
COMMENT ON COLUMN public."company"."group" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "keep" "pg_catalog"."bool" DEFAULT true NOT NULL;
COMMENT ON COLUMN public."company"."keep" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "marketing_budget" "pg_catalog"."numeric";
COMMENT ON COLUMN public."company"."marketing_budget" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "number_of_employees" "pg_catalog"."int4";
COMMENT ON COLUMN public."company"."number_of_employees" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "rank_frequency" "pg_catalog"."text";
COMMENT ON COLUMN public."company"."rank_frequency" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "rank_history" "pg_catalog"."jsonb";
COMMENT ON COLUMN public."company"."rank_history" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "rank_last_year" "pg_catalog"."int4";
COMMENT ON COLUMN public."company"."rank_last_year" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "rank_stage" "pg_catalog"."text";
COMMENT ON COLUMN public."company"."rank_stage" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "sponsor_tier" "pg_catalog"."text";
COMMENT ON COLUMN public."company"."sponsor_tier" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "sponsor_tier_rank" "pg_catalog"."int4";
COMMENT ON COLUMN public."company"."sponsor_tier_rank" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "startup" "pg_catalog"."bool";
COMMENT ON COLUMN public."company"."startup" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "subcategory" "pg_catalog"."text";
COMMENT ON COLUMN public."company"."subcategory" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "summit_interest" "pg_catalog"."text"[];
COMMENT ON COLUMN public."company"."summit_interest" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."company" ADD COLUMN "total_revenue" "pg_catalog"."numeric";
COMMENT ON COLUMN public."company"."total_revenue" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."contact" ADD COLUMN "emails_clicked" "pg_catalog"."int4" DEFAULT 0 NOT NULL;
COMMENT ON COLUMN public."contact"."emails_clicked" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."contact" ADD COLUMN "emails_delivered" "pg_catalog"."int4" DEFAULT 0 NOT NULL;
COMMENT ON COLUMN public."contact"."emails_delivered" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."contact" ADD COLUMN "emails_opened" "pg_catalog"."int4" DEFAULT 0 NOT NULL;
COMMENT ON COLUMN public."contact"."emails_opened" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."contact" ADD COLUMN "emails_replied" "pg_catalog"."int4" DEFAULT 0 NOT NULL;
COMMENT ON COLUMN public."contact"."emails_replied" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."contact" ADD COLUMN "key_contact" "pg_catalog"."text"[];
COMMENT ON COLUMN public."contact"."key_contact" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."contact" ADD COLUMN "last_activity_date" "pg_catalog"."timestamptz";
COMMENT ON COLUMN public."contact"."last_activity_date" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."contact" ADD COLUMN "last_email_click_date" "pg_catalog"."timestamptz";
COMMENT ON COLUMN public."contact"."last_email_click_date" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."contact" ADD COLUMN "last_email_open_date" "pg_catalog"."timestamptz";
COMMENT ON COLUMN public."contact"."last_email_open_date" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."contact" ADD COLUMN "last_email_send_date" "pg_catalog"."timestamptz";
COMMENT ON COLUMN public."contact"."last_email_send_date" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."contact" ADD COLUMN "unsubscribed_all_email" "pg_catalog"."bool" DEFAULT false NOT NULL;
COMMENT ON COLUMN public."contact"."unsubscribed_all_email" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."list" ADD COLUMN "entity_types" "pg_catalog"."text"[] DEFAULT '{}'::text[] NOT NULL;
COMMENT ON COLUMN public."list"."entity_types" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."list" ADD COLUMN "last_refreshed_at" "pg_catalog"."timestamptz";
COMMENT ON COLUMN public."list"."last_refreshed_at" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."task" ADD COLUMN "assigned_to" "pg_catalog"."text";
COMMENT ON COLUMN public."task"."assigned_to" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."task" ADD COLUMN "meta" "pg_catalog"."jsonb" DEFAULT '{}'::jsonb NOT NULL;
COMMENT ON COLUMN public."task"."meta" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
ALTER TABLE public."task" ADD COLUMN "origin" "pg_catalog"."text";
COMMENT ON COLUMN public."task"."origin" IS 'P8R1 transitional reconstruction from candidate catalog; ownership remains subject to CSD review.';
